apiVersion: v1
kind: Pod
metadata:
  name: redis-hostpath
spec:
  containers:
  - image: redis
    name: redis-conatainer
    volumeMounts:
    - mountPath: /test-mnt
      name: test-vol
  volumes:
  - name: test-vol
    hostPath:
      path: /test-vol 
