apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvebs
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  awsElasticBlockStorage:
    name: my-data
    type: ext4
