apiVersion: batch/v1
kind: Job
metadata:
  name: ubu
spec:
  template:
    spec:
      containers:
      - name: ubuntu
        image: ubuntu
        command:
         - "bin/bash"
         - "-c"
         - "for i in 9 8 7 6 5 4 3 2 1 : do echo $i : done"
      restartPolicy: Never
     
