apiVersion: v1
kind: Pod
metadata:
  name: pv-pd
spec:
  containers:
  - image: nginx
    name: web-app2
    volumeMounts:
    - name: test-volume
      mountPath: /test-pd
  volumes:
  - name: test-volume
    persistentVolumeClaim:
      claimName: my-disk-claim
