apiVersion: v1
kind: Pod
metadata:
  name: test-pd
spec:
  containers:
  - image: tomcat
    name: web-app
    volumeMounts:
    - name: cache-volume
      mountPath: /cache
  volumes:
  - name: cache-volume
    emptyDir: {} 
