apiVersion: v1
kind: Pod
metadata:
   name: redis-hp
spec:
   containers:
      - image: redis
        name: redis-container
        volumeMounts:
        - mountPath: /test-mnt
          name: test-vol
   volumes:
      - name: test-vol
        hostPath:
               path: /test-vol
